(import (scheme write))

(display "An ash I know there stands,\n")
(display "Yggdrasill is its name,\n")
(display "a tall tree, showered\n")
(display "with shining loam.\n")
(display "From there come the dews\n")
(display "that drop in the valleys.\n")
(display "It stands forever green over\n")
(display "Urðr's well.\n")
