(define-library (core bool)
(import (core primitives))
(import (core intrinsics))
(import (rename (core intrinsics) (%procedure? procedure?)
                                  (%symbol? symbol?)
                                  (%eq? eq?)
                                  (%eqv? eqv?)
                                  (%equal? equal?)))
(export not boolean? procedure? symbol? eq? eqv? equal?)
(begin
(define (not x) (if x #f #t))
(define (boolean? x) (if (eq? x #t) #t (eq? x #f)))
))
